gcloud compute instances create de-zoomcamp \
    --project=dtc-de-course-412716 \
    --zone=europe-west4-c \
    --machine-type=e2-standard-4 \
    --network-interface=network-tier=PREMIUM,stack-type=IPV4_ONLY,subnet=default \
    --maintenance-policy=MIGRATE \
    --provisioning-model=STANDARD \
    --service-account=720491610261-compute@developer.gserviceaccount.com \
    --scopes=https://www.googleapis.com/auth/devstorage.read_only,https://www.googleapis.com/auth/logging.write,https://www.googleapis.com/auth/monitoring.write,https://www.googleapis.com/auth/servicecontrol,https://www.googleapis.com/auth/service.management.readonly,https://www.googleapis.com/auth/trace.append \
    --create-disk=auto-delete=yes,boot=yes,device-name=de-zoomcamp,image=projects/ubuntu-os-cloud/global/images/ubuntu-2004-focal-v20240125,mode=rw,size=30,type=projects/dtc-de-course-412716/zones/europe-west4-c/diskTypes/pd-balanced \
    --no-shielded-secure-boot \
    --shielded-vtpm \
    --shielded-integrity-monitoring\
    --labels=goog-ec-src=vm_add-gcloud \
    --reservation-affinity=any